In [67]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats as ss
%matplotlib inline

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix

In [89]:
df_draft = pd.read_csv('../data/clean_nfl_draft.csv')
df_draft.head()

Player_Id  Year  Rnd  Pick   Tm           Player  Pos Position Standard  \
0  WinsJa00  2015  1.0     1  TAM   Jameis Winston   QB                QB   
1  MariMa01  2015  1.0     2  TEN   Marcus Mariota   QB                QB   
2  FowlDa00  2015  1.0     3  JAX     Dante Fowler  OLB                LB   
3  CoopAm00  2015  1.0     4  OAK     Amari Cooper   WR                WR   
4  ScheBr00  2015  1.0     5  WAS  Brandon Scherff    T                 T   

   First4AV   Age      ...       Rush_Yds  Rush_TDs    Rec  Rec_Yds  Rec_Tds  \
0        13  21.0      ...          311.0       7.0    0.0      0.0      0.0   
1         9  21.0      ...          516.0       4.0    1.0     41.0      1.0   
2         0  21.0      ...            0.0       0.0    0.0      0.0      0.0   
3         9  21.0      ...           -3.0       0.0  134.0   1970.0      9.0   
4         7  23.0      ...            0.0       0.0    0.0      0.0      0.0   

    Tkl  Def_Int   Sk  College/Univ  carrer_years  
0   0.0      0.0  0.0   Florida St.           2.0  
1   0.0      0.0  0.0        Oregon           2.0  
2  16.0      0.0  2.5       Florida           2.0  
3   0.0      0.0  0.0       Alabama           2.0  
4   0.0      0.0  0.0          Iowa           2.0  

[5 rows x 33 columns]

In [90]:
len(df_draft)

7052

In [98]:
df_draft.drop(df_draft.index[df_draft['Position Standard'] == 'C'], inplace = True)
df_draft.drop(df_draft.index[df_draft['Position Standard'] == 'T'], inplace = True)
df_draft.drop(df_draft.index[df_draft['Position Standard'] == 'G'], inplace = True)
df_draft.drop(df_draft.index[df_draft['Position Standard'] == 'K'], inplace = True)
df_draft.drop(df_draft.index[df_draft['Position Standard'] == 'P'], inplace = True)

'''df_draft = df_draft[df_draft.'Position Standard' != 'C']
df_draft = df_draft[df_draft.'Position Standard' != 'T']
df_draft = df_draft[df_draft.'Position Standard' != 'G']
df_draft = df_draft[df_draft.'Position Standard' != 'K']
df_draft = df_draft[df_draft.'Position Standard' != 'P']'''

"df_draft = df_draft[df_draft.'Position Standard' != 'C']\ndf_draft = df_draft[df_draft.'Position Standard' != 'T']\ndf_draft = df_draft[df_draft.'Position Standard' != 'G']\ndf_draft = df_draft[df_draft.'Position Standard' != 'K']\ndf_draft = df_draft[df_draft.'Position Standard' != 'P']"

In [99]:
len(df_draft)

5828

In [100]:
df_draft.head(15)

Player_Id  Year  Rnd  Pick   Tm            Player  Pos Position Standard  \
0   WinsJa00  2015  1.0     1  TAM    Jameis Winston   QB                QB   
1   MariMa01  2015  1.0     2  TEN    Marcus Mariota   QB                QB   
2   FowlDa00  2015  1.0     3  JAX      Dante Fowler  OLB                LB   
3   CoopAm00  2015  1.0     4  OAK      Amari Cooper   WR                WR   
5   WillLe02  2015  1.0     6  NYJ  Leonard Williams   DE                DE   
6   WhitKe00  2015  1.0     7  CHI       Kevin White   WR                WR   
7   BeasVi00  2015  1.0     8  ATL       Vic Beasley  OLB                LB   
9   GurlTo01  2015  1.0    10  STL       Todd Gurley   RB                RB   
10  WaynTr00  2015  1.0    11  MIN       Trae Waynes   CB                DB   
11  ShelDa01  2015  1.0    12  CLE     Danny Shelton   NT                DT   
13  ParkDe01  2015  1.0    14  MIA    DeVante Parker   WR                WR   
14  GordMe00  2015  1.0    15  SDG     Melvin Gordon   RB                RB   
15  JohnKe04  2015  1.0    16  HOU     Kevin Johnson   CB                DB   
16  ArmsAr01  2015  1.0    17  SFO     Arik Armstead   DT                DT   
17  PeteMa00  2015  1.0    18  KAN     Marcus Peters   CB                DB   

    First4AV   Age      ...       Rush_Yds  Rush_TDs    Rec  Rec_Yds  Rec_Tds  \
0         13  21.0      ...          311.0       7.0    0.0      0.0      0.0   
1          9  21.0      ...          516.0       4.0    1.0     41.0      1.0   
2          0  21.0      ...            0.0       0.0    0.0      0.0      0.0   
3          9  21.0      ...           -3.0       0.0  134.0   1970.0      9.0   
5          9  21.0      ...            0.0       0.0    0.0      0.0      0.0   
6          0  23.0      ...            9.0       0.0   19.0    187.0      0.0   
7          7  23.0      ...            0.0       0.0    0.0      0.0      0.0   
9          8  21.0      ...         1697.0      14.0   47.0    390.0      0.0   
10         1  23.0      ...            0.0       0.0    0.0      0.0      0.0   
11         6  22.0      ...            0.0       0.0    0.0      0.0      0.0   
13         3  22.0      ...            0.0       0.0   64.0    979.0      5.0   
14         5  22.0      ...         1479.0       9.0   66.0    538.0      2.0   
15         5  23.0      ...            0.0       0.0    0.0      0.0      0.0   
16         1  21.0      ...            0.0       0.0    0.0      0.0      0.0   
17        11  22.0      ...            0.0       0.0    0.0      0.0      0.0   

     Tkl  Def_Int    Sk   College/Univ  carrer_years  
0    0.0      0.0   0.0    Florida St.           2.0  
1    0.0      0.0   0.0         Oregon           2.0  
2   16.0      0.0   2.5        Florida           2.0  
3    0.0      0.0   0.0        Alabama           2.0  
5   56.0      0.0   9.0            USC           2.0  
6    0.0      0.0   0.0  West Virginia           2.0  
7   44.0      1.0  13.5        Clemson           2.0  
9    0.0      0.0   0.0        Georgia           2.0  
10  54.0      2.0   0.0   Michigan St.           2.0  
11  42.0      0.0   1.5     Washington           2.0  
13   0.0      0.0   0.0     Louisville           2.0  
14   0.0      0.0   0.0      Wisconsin           2.0  
15  65.0      1.0   0.0    Wake Forest           2.0  
16  23.0      0.0   4.5         Oregon           2.0  
17  79.0     13.0   0.0     Washington           2.0  

[15 rows x 33 columns]

In [101]:
set(df_draft['Position Standard'])

{'DB', 'DE', 'DT', 'FB', 'LB', 'QB', 'RB', 'TE', 'WR'}

In [102]:
idx_sk = list(df_draft.columns).index('Sk')
idx_cmp = list(df_draft.columns).index('Cmp')

### Train Test Split

In [103]:
labels_class = df_draft.columns[idx_cmp:idx_sk+1]

In [104]:
class_data = df_draft[labels_class]
target_data = df_draft['Position Standard']

In [105]:
X_train, X_test, y_train, y_test = train_test_split(class_data, target_data, test_size = 0.33)

### Decision Trees

In [106]:
dtree = DecisionTreeClassifier()

In [107]:
dtree.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

### Prediction and Evaluation

In [108]:
predictions = dtree.predict(X_test)

In [109]:
print(classification_report(y_test,predictions))

             precision    recall  f1-score   support

         DB       0.68      0.66      0.67       453
         DE       0.43      0.42      0.43       200
         DT       0.40      0.26      0.31       184
         FB       0.21      0.20      0.21        30
         LB       0.37      0.56      0.44       317
         QB       0.98      0.94      0.96        89
         RB       0.87      0.82      0.84       222
         TE       0.66      0.51      0.57       143
         WR       0.75      0.70      0.72       286

avg / total       0.62      0.60      0.60      1924



In [110]:
print(confusion_matrix(y_test,predictions))

[[300  14  14   0 124   0   0   0   1]
 [ 21  84  37   1  56   0   0   1   0]
 [ 33  53  47   0  51   0   0   0   0]
 [  0   0   0   6   4   1  13   0   6]
 [ 76  44  20   0 176   0   0   0   1]
 [  0   0   0   0   4  84   0   0   1]
 [  0   0   0  13  18   1 181   2   7]
 [  0   0   0   2  15   0   3  73  50]
 [  8   0   0   6  27   0  10  35 200]]


### Random Forests

In [130]:
from sklearn.ensemble import RandomForestClassifier
rf_class = RandomForestClassifier(n_estimators=100)
rf_class.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [131]:
rf_class_predict = rf_class.predict(X_test)

In [132]:
print(classification_report(y_test,rf_class_predict))

             precision    recall  f1-score   support

         DB       0.72      0.66      0.69       453
         DE       0.44      0.46      0.45       200
         DT       0.46      0.30      0.37       184
         FB       0.50      0.17      0.25        30
         LB       0.40      0.60      0.48       317
         QB       0.98      0.94      0.96        89
         RB       0.88      0.89      0.88       222
         TE       0.65      0.50      0.57       143
         WR       0.76      0.73      0.74       286

avg / total       0.64      0.63      0.63      1924



In [133]:
print(confusion_matrix(y_test,rf_class_predict))

[[301  21  12   0 117   1   0   0   1]
 [ 16  92  36   1  53   1   0   1   0]
 [ 26  51  56   0  51   0   0   0   0]
 [  0   0   0   5   3   0  18   0   4]
 [ 68  41  18   0 189   0   0   0   1]
 [  1   0   0   0   3  84   0   0   1]
 [  0   0   0   3  16   0 197   1   5]
 [  0   0   0   1  16   0   1  72  53]
 [  4   3   0   0  26   0   9  36 208]]
